import Head from "next/head"
import { createContext, useContext, useRef } from "react"
import AlwayShowOnDisplay from "../../components/AlwayShowOnDisplay"
import Goal from "../../components/Goal"
import Peudo from "../../components/Peudo"
import TeamTable from "../../components/TeamTable"
import Progress from "../../components/Progress"
import MeetingMinutes from "../../components/MeetingMinutes"

export const targetContext = createContext()

export default function Home() {
	const target1Ref = useRef()
	const target2Ref = useRef()
	const target3Ref = useRef()
	const target4Ref = useRef()
	const target5Ref = useRef()
	const target6Ref = useRef()

	const targets = {
		goalRef: target1Ref,
		teamTableRef: target2Ref,
		navigaRef: target4Ref,
		containerRef: target3Ref,
		processRef: target5Ref,
		mettingRef: target6Ref,
	}

	return (
		<>
			<Head>
				<title>Hệ thống quản lý cửa hàng thức ăn nhanh</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<targetContext.Provider value={targets}>
				<div ref={target3Ref}>
					<AlwayShowOnDisplay refTarget={target4Ref} />
					<Goal refTarget={target1Ref} />
					<TeamTable refTarget={target2Ref} />
					<Progress refTarget={target5Ref} />
					<MeetingMinutes refTarget={target6Ref} />
					<Peudo />
				</div>
			</targetContext.Provider>
		</>
	)
}
