import Head from "next/head"
import Goal from "../../components/Goal"
import Intro from "../../components/Intro"
import Peudo from "../../components/Peudo"

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='mx-4 my-8 overflow-hidden'>
				<h1 className='fixed opacity-50 op top-0 left-1/2 translate-x-[-50%] font-bold'>
					JAVA PROJECT
				</h1>

				<Goal />
				<Intro />
				<Peudo />
			</main>
		</>
	)
}
