import Head from "next/head"
import { motion } from "framer-motion"
import { textAnimate } from "../../utils/farmer_motion"

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<motion.div
					className='w-full h-screen text-3xl font-bold'
					initial={"offscreen"}
					whileInView={"onscreen"}
					viewport={{ once: false, amount: 1 }}
					transition={{ staggerChildren: 0.5 }}
				>
					<motion.h1 variants={textAnimate}>A</motion.h1>
					<motion.h1 variants={textAnimate}>B</motion.h1>
					<motion.h1 variants={textAnimate}>C</motion.h1>
					<motion.h1 variants={textAnimate}>D</motion.h1>
					<motion.h1 variants={textAnimate}>E</motion.h1>
					<motion.h1 variants={textAnimate}>F</motion.h1>
				</motion.div>
			</main>
		</>
	)
}
